const data = {
    '1': {
        id: 1,
        name: 'iPhone 12',
        imgid: '15PaG2EQ_f9SYz_eTPOn2WOqQIhr6DVSn',
        description:'A common "affordable" flagship iPhone released in 2020 that has now sold over 100 million units and was the most popular phone globally in 2021. Apple prides itself on providing sustainable options, an ambitious CO2 reduction goal, and seek to use mostly reclycled materials for their products, including the iPhone 12.',
        productionstatsid: 1,
        electricitykwh: 2,
        steeliron: 0.036,
        cement: 0,
        plastic: 0.046,
        glass: 0.032,
        latex: 0,
        rubber: 0,
        copper: 0.006,
        silver: 0.001,
        aluminum: 0.034,
        textile: 0,
        paper: 0,
    },
    '2': {
        id: 2,
        name: 'MacBook Air M1 2020',
        imgid: '',
        description: 'MacBook Air with M1 is an incredibly portable laptop — its nimble and quick, with a silent, fanless design and a beautiful Retina display. Thanks to its slim profile and all‑day battery life, this Air moves at the speed of lightness. Apple prides itself on providing sustainable options, an ambitious CO2 reduction goal, and seek to use mostly reclycled materials for their products, including this MacBook Air.',
        productionstatsid: 2,
        electricitykwh: 0.061,
        steeliron: 0,
        cement: 0,
        plastic: 0.127,
        glass: 0,
        latex: 0,
        rubber: 0,
        copper: 0.03,
        silver: 0.05,
        aluminum: 1.02,
        textile: 0,
        paper: 0,
    },
    '3': {
        id: 3,
        name: 'Clock',
        imgid: '',
        description: 'A common analog clock, with similar models being manufactured and sold worldwide. A simple yet reliable design.',
        productionstatsid: 3,
        electricitykwh: 0.003,
        steeliron: 0,
        cement: 0,
        plastic: 0.5,
        glass: 0.3,
        latex: 0,
        rubber: 0,
        copper: 0,
        silver: 0,
        aluminum: 1,
        textile: 0,
        paper: 0,
    },
    '4': {
        id: 4,
        name: 'Panasonic projector',
        imgid: '16MUDcI9NUImUZ1Try3qTrKiiJ4RLXJZH',
        description: 'Made by one of the leading projector brands, this projector and ones similar to it are in classrooms, offices, and homes worldwide. Panasonic itself is a leader in environmentally sustainable practices, but does not have a significant goal to reduce their CO2 emissions.',
        productionstatsid: 4,
        electricitykwh: 0.295,
        steeliron: 0.036,
        cement: 0,
        plastic: 0.26,
        glass: 0.032,
        latex: 0,
        rubber: 0,
        copper: 0.05,
        silver: 0.07,
        aluminum: 0.06,
        textile: 0,
        paper: 0,
    },
    '5': {
        id: 5,
        name: 'Philips Fluorescent Lamp',
        imgid: '1D8Jn7ZY8SL7Z8LvNjnSqgYu5YLe8qTKu',
        description: 'These flourescent lamps are all over the world in schools and offices and with a $14 Billion market, it is clear that they are very popular. Although flourescent bulbs are 5 times more efficient than incandescent bulbs, they are still only around 20% as efficient as LEDs. ',
        productionstatsid: 5,
        electricitykwh: 0.032,
        steeliron: 0,
        cement: 0,
        plastic: 0,
        glass: 0.41,
        latex: 0,
        rubber: 0,
        copper: 0.05,
        silver: 0.05,
        aluminum: 0,
        textile: 0,
        paper: 0,
    },
    '6': {
        id: 6,
        name: 'Carpet Flooring',
        imgid: '',
        description:'A common flooring material, carpet is primarily made of nylon, which is derived from crude oil and is very costly. Though other synthetic materials are used, most have similarly expensive oil and water requirements',
        productionstatsid: 6,
        electricitykwh: 0,
        steeliron: 0,
        cement: 0,
        plastic: 0,
        glass: 0,
        latex: 0,
        rubber: 0,
        copper: 0,
        silver: 0,
        aluminum: 0,
        textile: 100,
        paper: 0,
    },
    '7': {
        id: 7,
        name: '',
        imgid: '',
        description: '',
        productionstatsid: 7,
        electricitykwh: 2,
        steeliron: 0.036,
        cement: 0,
        plastic: 0.046,
        glass: 0.032,
        latex: 0,
        rubber: 0,
        copper: 0.006,
        silver: 0.001,
        aluminum: 0.034,
        textile: 0,
        paper: 0,
    },
};

export default data;